#!/bin/bash
apt install -y zsh

apt install -y   apt-transport-https     ca-certificates     curl     gnupg-agent     software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
apt-get update
apt install -y docker-ce docker-ce-cli containerd.io docker-compose

snap install kubectl --classic

apt install -y build-essential libssl-dev pkg-config libpq-dev
