# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.222.11"

  # Attempt to share the host home dir
  config.vm.synced_folder "../..", "/home/vagrant/host"
  config.vm.synced_folder "..", "/home/vagrant/.dotfiles"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Default vagrant"
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    OVERWRITE_ALL=true .dotfiles/script/bootstrap
    .dotfiles/script/install
    # provision is run as root and so the default user may not have access to its own files
    chown vagrant:vagrant /home/vagrant/.nvm
  SHELL
end
